import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'

import {ThemeProvider} from "@/provider/theme-provider";
import NextNProgressClient from "@/components/ui/next-progress";

import "./globals.css";
import {cn} from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider>
        <html lang="en" suppressHydrationWarning>
          <body className={cn("bg-secondary", inter.className)}>
              <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                  <NextNProgressClient />
                  {children}
              </ThemeProvider>
          </body>
        </html>
      </ClerkProvider>
  );
}
